apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
	- name: test-container
  	image: gcr.io/google_containers/busybox
  	command: [ "/bin/sh", "-c", "ls -la /etc/config" ]
  	volumeMounts:
  	- name: config-volume
    	  mountPath: /etc/config
  volumes:
	- name: config-volume
  	  configMap:
    	    name: my-files
  restartPolicy: Never
