apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: kube-system
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            # Use the same image as specified in the etcd pod
            image: k8s.gcr.io/etcd:3.2.24
            env:
              - name: ETCDCTL_API
                value: "3"
                command: ["/bin/sh"]
                args: ["-c", "etcdctl --endpoints=https://127.0.0.1:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt                    --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key snapshot save /backup/etcd-snapshot-$(date +%Y-%m-%d_%H:%M:%S_%Z).db"]
            volumeMounts:
              - mountPath: /etc/kubernetes/pki/etcd
                name: etcd-certs
                readOnly: true
              - mountPath: /backup
                name: backup
        restartPolicy: OnFailure
        hostNetwork: true
        volumes:
          - name: etcd-certs
            hostPath:
                path: /etc/kubernetes/pki/etcd
                type: DirectoryOrCreate
          - name: backup
            hostPath:
              path: /data/backup
              type: DirectoryOrCreate
